---
- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - rng-tools
    - ipa-server
    - ipa-server-dns

- name: Install rng-tools
  yum:
    name: "rng-tools"
    update_cache: yes
    state: installed

- name: Add more entropy for the random generation for the encryption key of the Kerberos database
  lineinfile:
    path: /etc/sysconfig/rngd
    line: "EXTRAOPTIONS=\"-r /dev/urandom\""
    state: present
    create: yes

- name: Activate and enable rngd
  service:
    name: rngd
    state: started
    enabled: yes
